### DISCUSSION TITLE
mariadb username and password?

### DISCUSSION THREAD

**Discussion by jj-uk** [hassio-addons/addon-nginx-proxy-manager#364] [Q&A] [answered]
What's the username and password for the "nginxproxymanager" database in mariadb ?

**Comment by Gredev76** [comment]
You set this up yourself as part of the MariaDB configuration. If you are running Home Assistant Operating System and installed MariaDB as an add-on you can go to Settings->Add-ons->MariaDB and check under the Configuration tab.

**Reply by jj-uk** [reply]
The only config in  Settings->Add-ons->MariaDB I have is for the 'homeassistant' database. 

When NPM first started, it created a database called 'nginxproxymanager'. I'd like the username and password for that database (and also the root user password for the Mariadb).

**Reply by Gredev76** [reply]
In my setup, which followed the standard procedure afaik, the username and password listed under the MariaDB configuration tab also grants me access to the nginxproxymanager database.

Have you tried installing the add-on phpMyAdmin and connecting to MariaDB to see if you can see/access the nginxproxymanager db there?

**Reply by jj-uk** [reply]
Here's my MariaDB config:

```
databases:
  - homeassistant
logins:
  - password: <removed>
    username: homeassistant
rights:
  - database: homeassistant
    username: homeassistant

```
It only allows access to the 'homeassistant' database.
I installed phpMyAdmin to try that, but it won't start. Gets stuck when starting NGinx `INFO: Starting NGinx....`.

I'm using Webyog community edition to login to the database.
