### ISSUE TITLE
Add to Documentation YAML config changes

### ISSUE THREAD

**Issue by bkvargyas** [hassio-addons/addon-nginx-proxy-manager#273]
The Documentation needs to be updated to include the following configuration to make this work with later releases of home-assistant:

Add to configuration.yaml:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.0.0.0/8

**Comment by Phillomath** [comment]
Thank you this fixed my proxy forwarding after an update! Just had to tweak the indenting like so:
```
http:
    use_x_forwarded_for: true
    trusted_proxies:
    - 172.0.0.0/8
```
 
Prior to this I was getting an "Error 400" when going to the external URL.
