### ISSUE TITLE
Docker IP banned instead of public IP

### ISSUE THREAD

**Issue by naimadfpv** [hassio-addons/addon-nginx-proxy-manager#495]
# Problem/Motivation

Setup Addon to get remote access to my HA. It’s working but I want to ban public ip address for failed logins

## Expected behavior

In configuration.yaml

http:
  ip_ban_enabled: true

Should ban public IP instead of docker IP

## Actual behavior

Docker IP gets banned when login attempts failed.

## Steps to reproduce

http:
  use_x_forwarded_for: true
  ip_ban_enabled: true
  login_attempts_threshold: 5
  trusted_proxys:
    - <IP_of_NPM> 

## Proposed changes

IP of Remote Host instead of Docker IP

**Comment by akrigator** [comment]
Seems that this may be configred with Access List  in NPM  <img width="1222" alt="image" src="https://github.com/hassio-addons/addon-nginx-proxy-manager/assets/695335/119e025b-02d0-4c0c-94de-28741a46ae6b">

**Comment by naimadfpv** [comment]
Yes I know but I want the way with npm. Thank you anyways.

What I read is that you have to set X-Forwarded-For header setting for $remote_addr in NGINX. Maybe this could also be set in NPM?

**Comment by akrigator** [comment]
so,  i've  try 
```
http:
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.88.0/24
    - 172.30.232.0/23
    - 172.30.32.0/23
    - 127.0.0.1 # Add the localhost IPv4 address
    - ::1 # Add the localhost IPv6 address
```

homeassistant domain in NPM does not have any Custom location or Custom Nginx Configuration.

After 5 failed logins my external ip goes to ban:
```
cat /root/config/ip_bans.yaml 

97.25.131.114:
  banned_at: '2024-01-05T22:51:47.997039+00:00'
```
