### ISSUE TITLE
Home Assistant trusted_proxies setting

### ISSUE THREAD

**Issue by respectTheCode** [hassio-addons/addon-nginx-proxy-manager#53]
# Problem/Motivation

Without the `use_x_forwarded_for` setting all requests come from the proxy and you can easily get in a situation where the proxy gets ip banned. This is most likely not a bug but is just something that needs to be documented.

## Expected behavior

Home Assistant should see and use the IP of the source

## Actual behavior

Home Assistant uses the proxies IP

## Tried

Here is the config that I think should work but is not

```
http:
  base_url: ....

  use_x_forwarded_for: true
  trusted_proxies:
    - 172.16.0.0/12
  
  ip_ban_enabled: true
  login_attempts_threshold: 5
```
